name: movil
description: "cliente movil para gestion del programa deporte para todos"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.5.0

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  dio: ^5.7.0
  provider: ^6.1.2
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  fonts:
  #Tipografia definida en los lineamientos de diseño de la division tic
      - family: OpenSans
        fonts:
          - asset: assets\fonts\Open_Sans\static\OpenSans-SemiBoldItalic.ttf
          - asset: assets\fonts\Open_Sans\static\OpenSans-SemiBold.ttf
          - asset: assets\fonts\Open_Sans\static\OpenSans-Regular.ttf
          - asset: assets\fonts\Open_Sans\static\OpenSans-MediumItalic.ttf
          - asset: assets\fonts\Open_Sans\static\OpenSans-Medium.ttf
          - asset: assets\fonts\Open_Sans\static\OpenSans-LightItalic.ttf
          - asset: assets\fonts\Open_Sans\static\OpenSans-Light.ttf
          - asset: assets\fonts\Open_Sans\static\OpenSans-Italic.ttf
          - asset: assets\fonts\Open_Sans\static\OpenSans-ExtraBoldItalic.ttf
          - asset: assets\fonts\Open_Sans\static\OpenSans-ExtraBold.ttf
          - asset: assets\fonts\Open_Sans\static\OpenSans-BoldItalic.ttf
          - asset: assets\fonts\Open_Sans\static\OpenSans-Bold.ttf
          - asset: assets\fonts\Open_Sans\static\OpenSans_SemiCondensed-SemiBoldItalic.ttf
          - asset: assets\fonts\Open_Sans\static\OpenSans_SemiCondensed-SemiBold.ttf
          - asset: assets\fonts\Open_Sans\static\OpenSans_SemiCondensed-Regular.ttf
          - asset: assets\fonts\Open_Sans\static\OpenSans_SemiCondensed-MediumItalic.ttf
          - asset: assets\fonts\Open_Sans\static\OpenSans_SemiCondensed-Medium.ttf
          - asset: assets\fonts\Open_Sans\static\OpenSans_SemiCondensed-LightItalic.ttf
          - asset: assets\fonts\Open_Sans\static\OpenSans_SemiCondensed-Light.ttf
          - asset: assets\fonts\Open_Sans\static\OpenSans_SemiCondensed-Italic.ttf
          - asset: assets\fonts\Open_Sans\static\OpenSans_SemiCondensed-ExtraBoldItalic.ttf
          - asset: assets\fonts\Open_Sans\static\OpenSans_SemiCondensed-ExtraBold.ttf
          - asset: assets\fonts\Open_Sans\static\OpenSans_SemiCondensed-BoldItalic.ttf
          - asset: assets\fonts\Open_Sans\static\OpenSans_SemiCondensed-Bold.ttf
          - asset: assets\fonts\Open_Sans\static\OpenSans_Condensed-SemiBoldItalic.ttf
          - asset: assets\fonts\Open_Sans\static\OpenSans_Condensed-SemiBold.ttf
          - asset: assets\fonts\Open_Sans\static\OpenSans_Condensed-Regular.ttf
          - asset: assets\fonts\Open_Sans\static\OpenSans_Condensed-MediumItalic.ttf
          - asset: assets\fonts\Open_Sans\static\OpenSans_Condensed-Medium.ttf
          - asset: assets\fonts\Open_Sans\static\OpenSans_Condensed-LightItalic.ttf
          - asset: assets\fonts\Open_Sans\static\OpenSans_Condensed-Light.ttf
          - asset: assets\fonts\Open_Sans\static\OpenSans_Condensed-Italic.ttf
          - asset: assets\fonts\Open_Sans\static\OpenSans_Condensed-ExtraBoldItalic.ttf
          - asset: assets\fonts\Open_Sans\static\OpenSans_Condensed-ExtraBold.ttf
          - asset: assets\fonts\Open_Sans\static\OpenSans_Condensed-BoldItalic.ttf
          - asset: assets\fonts\Open_Sans\static\OpenSans_Condensed-Bold.ttf
          - asset: assets\fonts\Open_Sans\OpenSans-VariableFont_wdth,wght.ttf
          - asset: assets\fonts\Open_Sans\OpenSans-Italic-VariableFont_wdth,wght.ttf
      
      - family: TitiliumWeb
        fonts:
          - asset: assets\fonts\Titillium_Web\TitilliumWeb-SemiBoldItalic.ttf
          - asset: assets\fonts\Titillium_Web\TitilliumWeb-SemiBold.ttf
          - asset: assets\fonts\Titillium_Web\TitilliumWeb-Regular.ttf
          - asset: assets\fonts\Titillium_Web\TitilliumWeb-LightItalic.ttf
          - asset: assets\fonts\Titillium_Web\TitilliumWeb-Light.ttf
          - asset: assets\fonts\Titillium_Web\TitilliumWeb-Italic.ttf
          - asset: assets\fonts\Titillium_Web\TitilliumWeb-ExtraLightItalic.ttf
          - asset: assets\fonts\Titillium_Web\TitilliumWeb-ExtraLight.ttf
          - asset: assets\fonts\Titillium_Web\TitilliumWeb-BoldItalic.ttf
          - asset: assets\fonts\Titillium_Web\TitilliumWeb-Bold.ttf
          - asset: assets\fonts\Titillium_Web\TitilliumWeb-Black.ttf

      - family: FiraSans
        fonts:
          - asset: assets\fonts\Fira_Sans\FiraSans-Black.ttf
          - asset: assets\fonts\Fira_Sans\FiraSans-BlackItalic.ttf
          - asset: assets\fonts\Fira_Sans\FiraSans-Bold.ttf
          - asset: assets\fonts\Fira_Sans\FiraSans-BoldItalic.ttf
          - asset: assets\fonts\Fira_Sans\FiraSans-ExtraBold.ttf
          - asset: assets\fonts\Fira_Sans\FiraSans-ExtraBoldItalic.ttf
          - asset: assets\fonts\Fira_Sans\FiraSans-ExtraLight.ttf
          - asset: assets\fonts\Fira_Sans\FiraSans-ExtraLightItalic.ttf
          - asset: assets\fonts\Fira_Sans\FiraSans-Italic.ttf
          - asset: assets\fonts\Fira_Sans\FiraSans-Light.ttf
          - asset: assets\fonts\Fira_Sans\FiraSans-LightItalic.ttf
          - asset: assets\fonts\Fira_Sans\FiraSans-Medium.ttf
          - asset: assets\fonts\Fira_Sans\FiraSans-MediumItalic.ttf
          - asset: assets\fonts\Fira_Sans\FiraSans-Regular.ttf
          - asset: assets\fonts\Fira_Sans\FiraSans-SemiBold.ttf
          - asset: assets\fonts\Fira_Sans\FiraSans-SemiBoldItalic.ttf
          - asset: assets\fonts\Fira_Sans\FiraSans-Thin.ttf
          - asset: assets\fonts\Fira_Sans\FiraSans-ThinItalic.ttf
      - family: Playfair
        fonts:
          - asset: assets\fonts\Playfair_Display\PlayfairDisplay-VariableFont_wght.ttf
          - asset: assets\fonts\Playfair_Display\PlayfairDisplay-VariableFont_wght.ttf
          - asset: assets\fonts\Playfair_Display\static\PlayfairDisplay-Black.ttf
          - asset: assets\fonts\Playfair_Display\static\PlayfairDisplay-Bold.ttf
          - asset: assets\fonts\Playfair_Display\static\PlayfairDisplay-BoldItalic.ttf
          - asset: assets\fonts\Playfair_Display\static\PlayfairDisplay-ExtraBold.ttf
          - asset: assets\fonts\Playfair_Display\static\PlayfairDisplay-ExtraBoldItalic.ttf
          - asset: assets\fonts\Playfair_Display\static\PlayfairDisplay-Italic.ttf
          - asset: assets\fonts\Playfair_Display\static\PlayfairDisplay-Medium.ttf
          - asset: assets\fonts\Playfair_Display\static\PlayfairDisplay-MediumItalic.ttf
          - asset: assets\fonts\Playfair_Display\static\PlayfairDisplay-Regular.ttf
          - asset: assets\fonts\Playfair_Display\static\PlayfairDisplay-SemiBold.ttf
          - asset: assets\fonts\Playfair_Display\static\PlayfairDisplay-SemiBoldItalic.ttf
  assets:
    - assets\images\1.jpg
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
